@extends('reports.base-pdf')

@section('content')
    <div class="section">
        <h2 class="section-title">Report Summary</h2>
        <p>This is a financial report generated by FinCore.</p>
        
        @if(isset($data) && is_array($data))
            <table>
                <thead>
                    <tr>
                        <th>Key</th>
                        <th>Value</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($data as $key => $value)
                        @if(is_array($value) || is_object($value))
                            @continue
                        @endif
                        <tr>
                            <td>{{ ucfirst(str_replace('_', ' ', $key)) }}</td>
                            <td>
                                @if(is_numeric($value) && strpos($key, 'amount') !== false || strpos($key, 'total') !== false)
                                    {{ number_format($value, 2) }}
                                @else
                                    {{ $value }}
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @endif
    </div>
    
    <div class="section">
        <div class="signature-line"></div>
        <div class="signature-label">Authorized Signature</div>
    </div>
@endsection
